# The following values should be added as environment variables with email and userKey being secrets:
#    MEND_URL: The instance URL of your Mend Organization - (https://saas.mend.io) for example.
#    MEND_EMAIL: Your email address; can be inserted as an Azure Pipelines environment variable.
#    MEND_USER_KEY: Your Mend user key; can be inserted as an Azure Pipelines environment variable.

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
    
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo Downloading Mend CLI
      curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
      echo Run Mend SCA scan
      mend dep -u -s *//$(System.TeamProject)//$(Build.Repository.Name)_$(Build.SourceBranchName)
    env:
      MEND_EMAIL: $(MEND_EMAIL)
      MEND_USER_KEY: $(MEND_USER_KEY)
      MEND_URL: 'https://saas.mend.io'
    displayName: 'Mend CLI SCA Scan'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'
